spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: NJben@1234
    url: jdbc:postgresql://192.168.1.74:5432/bellon_0
#    # 连接池-初始化大小
#    initial-size: 10
#    # 连接池-最大连接数
#    max-active: 100
#    # 最大等待时间
#    max-wait: 60000
#    # 连接池-最小空闲数
#    min-idle: 10
#    # 检测空闲连接
#    test-while-idle: true
#    # 最小空闲时间
#    min-evictable-idle-time-millis: 300000

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl