spring:
  # 一个实体类对应两张表，覆盖
  main:
    allow-bean-definition-overriding: true
  sharding-sphere:
    # 数据源配置
    datasource:
      # 数据源名称，多数据源以逗号分隔
      names: db0
      db0:
        type: com.zaxxer.hikari.HikariDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        jdbc-url: jdbc:mysql://192.168.1.73:3306/sharding_sphere_db1?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true
        username: root
        password: NJben@1234
    # 分片规则配置
    rules:
      sharding:
        # 分片算法配置
        sharding-algorithms:
          table-inline:
            # 分片算法类型
            type: INLINE
            props:
              # 分片算法的行表达式
              algorithm-expression: tbl_order_info_$->{order_type % 4}
        tables:
          # 逻辑表名称
          tbl_order_info:
            # 行表达式标识符可以使用 ${...} 或 $->{...}，但前者与 Spring 本身的属性文件占位符冲突，因此在 Spring 环境中使用行表达式标识符建议使用 $->{...}
            actual-data-nodes: db0.tbl_order_info_$->{1..4}
            # 分表策略
            table-strategy:
              standard:
                # 分片列名称
                sharding-column: order_type
                # 分片算法名称
                sharding-algorithm-name: table-inline
      # 属性配置
    props:
        # 展示修改以后的sql语句
      sql-show: true

mybatis:
  ##config-location: classpath:/mybatis-config.xml
  mapper-locations: classpath:/mapper/**/*.xml
