spring:
  datasource:
    url: jdbc:mysql://192.168.1.73:3306/leaf?serverTimezone=Asia/Shanghai&characterEncoding=utf8
    username: root
    password: NJben@1234

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  ##type-aliases-package: com.it.domain